[package]
name = "text_shader_image"
edition.workspace = true
version = "0.1.0"

[dependencies]
trivalibs.workspace = true
log.workspace = true
png.workspace = true
pollster.workspace = true
env_logger.workspace = true
flume.workspace = true
