[package]
name = "trivalibs_shaders"
version = "0.1.0"
edition.workspace = true

[dependencies]
spirv-std.workspace = true

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
glam.workspace = true
